### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by slavap** [Vertispan/gwt-uibinder#16]
Latest master branch.

gwt-uibinder-example-client: Compilation failure
[ERROR] /C:/Temp/gwt-uibinder-master/gwt-uibinder-example/gwt-uibinder-example-client/src/main/java/org/gwtproject/uibinder/example/view/newuibinder/NewSimpleFormView.java:[39,35] cannot access org.gwtproject.uibinder.example.view.newuibinder.NewSimpleFormView_MyUiBinderImpl
[ERROR]   bad source file: C:\Temp\gwt-uibinder-master\gwt-uibinder-example\gwt-uibinder-example-client\target\generated-sources\annotations\org\gwtproject\uibinder\example\view\newuibinder\NewSimpleFormView_MyUiBinderImpl.java
[ERROR]     file does not contain class org.gwtproject.uibinder.example.view.newuibinder.NewSimpleFormView_MyUiBinderImpl

Content of NewSimpleFormView_MyUiBinderImpl.java is only one line:
// .ui.xml template last modified: 1521834627218

**Comment by jhickman** [comment]
I'm wondering if this is due to compiling on Windows.  Possible wrong separator character (/ vs \).  More logging in the processor may help with this.   Incremental updates have been happening in the last few weeks if you would like to try again soon.

**Comment by slavap** [comment]
@jhickman Current master branch builds just fine.
